### ISSUE TITLE
add support for arguments

### ISSUE THREAD

**Issue by bjornwiberg** [eliba2/vim-node-inspect#1]
i would be very useful to pass the arguments when debugging node cli applications

apparently there is support for this in in node-inspect via `scriptArgs` https://github.com/eliba2/vim-node-inspect/blob/6443a67258ae75834e10639d97f91336bb6b33a6/node-inspect/lib/_inspect.js#L94

the arguments could be passed as an array like vs-code handles it, but here from `vim-node-config.json`
```json
{
  "args": [
    "-b", "${workspaceFolder}/tests/specs/asyncapi-example.yml",
    "-m", "${workspaceFolder}/tests/specs/asyncapi-example.yml"
   ]
}
```

**Comment by eliba2** [comment]
Its on the to-do list. Support for definitions in the config file will come first (as the plugin doesn't know of "${workspaceFolder}" or other definitions).

**Comment by bjornwiberg** [comment]
Great!
Maybe a way of solve this could be to use `:pwd` as **workspaceFolder**?

Is there any public roadmap available?

**Comment by eliba2** [comment]
Yes, I was thinking of that just as well (pwd == workspaceFolder).
And no, there is no public roadmap, only my personal notes. It will be available soon.

**Comment by eliba2** [comment]
Now arguments can be used, either by running NodeInspectStart(/Run) "xxx","yyy", or through the config file using "args":["one","two"].
${workspaceFolder} was also added.
cheers ;)
