### ISSUE TITLE
Executing code in current context

### ISSUE THREAD

**Issue by T-vK** [eliba2/vim-node-inspect#10]
Is there a way to execute in the current context without adding watches?
When I enter code in the log window I always get an error:
![image](https://user-images.githubusercontent.com/11368523/88904954-05876080-d256-11ea-90c0-65c98d57f36b.png)

It would be nice if I could just run code in that window, just like I can in a browser console while debugging.

**Comment by eliba2** [comment]
Hi, yes, use "repl" to go into repl mode where you can run commands. 
Its also possible to run a single command without going into repl mode by prepending the command with "exec" (eg `exec myvar`).
The reason for this is the originating node-inspect project integration . By default you are in command mode (see help for the available commands).

**Comment by eliba2** [comment]
It might be better to go repl mode by default. I'll check it out and keep this issue open.

**Comment by T-vK** [comment]
Great, thank you!
One more question: Is it possible to see the error message when there is a syntax error preventing a script from starting?

For example:

![image](https://user-images.githubusercontent.com/11368523/88918054-1b525100-d269-11ea-9272-8f1a9e47d9e3.png)

When I run it manually outside of vim, I would get a proper error message like:

```
/tmp/asd/index.js:2
console.log(2
            ^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
Instead of just `Debugger connection lost`.

**Comment by eliba2** [comment]
I'm not sure; I'll have to look into this.

**Comment by eliba2** [comment]
Recent version starts node repl by default.

**Comment by eliba2** [comment]
When I try to execute a script with an error (similar to the one you posted above in the example), I do get the error message in the node console. I want to try and reproduce this, can you point me to the node version you have and is it vim/nvim?

**Comment by T-vK** [comment]
node 12.18.2
vim 8.2

I simply have an empty folder with a single file called index.js with the following content:

```
console.log(1)
console.log(2
console.log(3)
```

In a bash (5.0.11(1)-release) console, I then open the file like this `vim index.js`. Then i simply Press F5 (I'm using the shortcuts from the readme).


Using the latest git version of your plugin, it looks like this:

![image](https://user-images.githubusercontent.com/11368523/89158936-16461800-d56f-11ea-8c68-fb73ca4e6dde.png)

So it still doesn't display the error.

**Comment by eliba2** [comment]
I can confirm it occurs from node version 12 and on.
Its a problem with node-inspect; I'll post a question there.

**Comment by eliba2** [comment]
nodejs/node#41792

**Comment by eliba2** [comment]
The problem was the child process ended before it had the chance of reading final stderr messages. Fixed in node-inspect, I'll PR there is possible.

**Comment by T-vK** [comment]
Thank you, I've tested it and it works now.
