### ISSUE TITLE
Debug NPM commands

### ISSUE THREAD

**Issue by iiison** [eliba2/vim-node-inspect#12]
Hi, thanks for the awesome plugin. I have a quick question though, is there a way to debug npm commands? Say, for example, I have a command `npm run test` which, in turn, calls Jest and then runs tests from my test file. I was wondering if there is a way to stop the execution at one of my test files.

**Comment by eliba2** [comment]
Hi,
Not at the moment. 
If you mean [this](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-support-for-npm-and-other-tools) , it'll probably will be available in the future.
Cheers,

**Comment by Lakshamana** [comment]
@eliba2 this is an awesome plugin indeed. Have you any updates on this? That would be great to address specific cases like debugging serverless applications

**Comment by eliba2** [comment]
@Lakshamana thanks, 
At the moment I'm working on another feature; I'll try and give it precedence.
