### ISSUE TITLE
Allow switching to a different port

### ISSUE THREAD

**Issue by AdrienLemaire** [eliba2/vim-node-inspect#13]
My usecase:

* node server runs with inspect on port 9229
* jest tests run with inspect on port 9230

When I want to debug a test, both the node server and jest server are running, hence both ports 9229 and 9230 can be inspected.

I was expecting the following configuration to work:

vim-node-config.json
```json
{
    "request": "attach",
    "port": 9229,
    "restart": true
}
```

vimrc
```vim
nnoremap <leader>nii :NodeInspectStart<cr>  
nnoremap <leader>nia :NodeInspectConnect("127.0.0.1:9230")<cr> 
```

I would press `<leader>nii` to listen to the node server, then press `<leader>nia` to switch to the test server. 
In reality, `<leader>nia` will also listen to 9229. It seems like the `vim-node-config.json` file takes priority over the arguments given to `NodeInspectConnect`. 

Shouldn't the priority order be reversed ? Or is my setup incorrect?

**Comment by eliba2** [comment]
You are right - the configuration file does takes precedence.
There's some wip which can solve this, which enables working with several configurations, so I'll keep this open meanwhile.

**Comment by eliba2** [comment]
Recent release added multiple configuration which handles this.
