### ISSUE TITLE
Error detected while processing function nodeinspect#NodeInspectConnect[20]

### ISSUE THREAD

**Issue by portothree** [eliba2/vim-node-inspect#16]
I'm getting the following error when I try to use `NodeInspectConnect` command:
```
Error detected while processing function nodeinspect#NodeInspectConnect[20]..<SNR>119_NodeInspectStart[3
5]..nodeinspect#utils#ConnectToBridge:
line   12:
E475: Invalid argument: localhost:
```
![](https://i.gyazo.com/4bf50410c91c6c4ffa804b6fde2f1674.png)

Env:

Node 14.17.0 
Vim 8.1

**Comment by portothree** [comment]
I can confirm this is a regression, before commit https://github.com/eliba2/vim-node-inspect/commit/c1a6ef67a9c05d9af2076229a3140a6cb13f3cc0 it was working flawless.
I have reverted the commit in my local repo, and it's working fine.

**Comment by eliba2** [comment]
Hi,
Can you provide me the exact command you are using (e.g. which parameter you use) - or if its through a configuration file - the file itself.

**Comment by eliba2** [comment]
I've managed to reproduce it; its a bad input in Vim (in neovim its alright; the "system" command does not accept List in Vim, though I don't see a difference in the docs). I'll just push a fix.

**Comment by portothree** [comment]
> Hi,
> Can you provide me the exact command you are using (e.g. which parameter you use) - or if its through a configuration file - the file itself.

I was using `NodeInspectConnect("127.0.0.1:9229")` without any configuration file.

**Comment by portothree** [comment]
Thanks for the fix and the work in this plugin, I can confirm it is working in my environment.
