### ISSUE TITLE
warning or error messages at exit 

### ISSUE THREAD

**Issue by laoshaw** [eliba2/vim-node-inspect#3]
trying to use this plugin, when I close a file I saw a few red messages fly-by at the bottom of vim triggered by this plugin, it went so fast I can not read them, is there a way for me to capture them into a file or somehow?

**Comment by laoshaw** [comment]
here is the "RED" error message during vim exit:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"~/vim_errors.txt" 5L, 257C
Error detected while processing function OnVimLeavePre[6]..OnNodeInspectExit[6]..<SNR>142_NodeInspectCleanup[5]..nodeinspect#utils#CloseChannel:
line    3:
E475: Invalid argument: 0
```

**Comment by eliba2** [comment]
Thanks, the problem was mixing vim and  nvim logic in a bad way. It is fixed.
As you probably noticed - getting the errors is done via "redir".

cheers;)
