### ISSUE TITLE
Stop then Start the same program give error messages

### ISSUE THREAD

**Issue by laoshaw** [eliba2/vim-node-inspect#4]
After I issued NodeInspectStop, then restart it with a NodeInspectStart, I saw two red messages:

```
Error detected while processing function nodeinspect#NodeInspectStart[13]..<SNR>144_NodeInspectStart[20]..nodeinspect#repl#ShowReplWindow:

E86: Buffer 2 does not exit
```

Re-issue NodeInspectStart will get back to normal.

**Comment by eliba2** [comment]
It is improper cleanup when exiting; fixed in the latest.
cheers
