### ISSUE TITLE
Setting highlights in vimrc does not work

### ISSUE THREAD

**Issue by adamraine** [eliba2/vim-node-inspect#6]
![image](https://user-images.githubusercontent.com/6752989/83178876-2d8c0380-a0ef-11ea-86a1-3f3ea1a78de8.png)
I customized the highlight values for the sign and breakpoint but it appears those values aren't working unless I hardcode the values into autoload/nodeinspect.vim.

**Comment by eliba2** [comment]
That's because it's local to the module.
I agree such option would make a great addition, it could be a quick win here.

**Comment by eliba2** [comment]
merged #7 ,
cheers;)
